blank_issues_enabled: true
contact_links:
    - name: Original plugin (Spaced Repetition by Stephen Mwangi)
      url: https://github.com/st3v3nmw/obsidian-spaced-repetition
      about: Problems that also happen in the original plugin can be reported there.
